version: '3.2'

services:
  portainer:
    image: "portainer/portainer"
    container_name: "portainer"
    restart: "no"
    ports:
      - "9999:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./var/portainer-data:/data"
    networks:
      - "default"

  php:
    build: "docker/php"
    container_name: "php"
    hostname: "php"
    working_dir: "/var/www"
    environment:
      USER_UID: "${USER_UID}"
      USER_GID: "${USER_GID}"
      XDEBUG_CONFIG: "${XDEBUG_CONFIG}"
      PHP_IDE_CONFIG: "serverName=symfony.local"
    restart: "always"
    ports:
      - "8741:80"
    volumes:
      - "./docker/php/vhosts:/etc/apache2/sites-enabled"
      - "/var/www/symfony5-rabbitmq-cqrs:/var/www"
      - "~/.composer:/home/www-data/.composer"
    networks:
      - "default"

  rabbitmq:
    build: "./docker/rabbitmq"
    container_name: "rabbitmq"
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    networks:
      - "default"

  db:
    build: "./docker/mysql"
    container_name: "mysql"
    hostname: "mysql"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
    ports:
      - "3306:3306"
    volumes:
      - "./var/mysql:/var/lib/mysql"
    networks:
      - "default"

networks:
  default:
    driver: "bridge"
